/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSubscriptionsRouteImport } from './routes/_authenticated/subscriptions'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedGuidaRouteImport } from './routes/_authenticated/guida'
import { Route as AuthenticatedGroupsRouteImport } from './routes/_authenticated/groups'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCitiesRouteImport } from './routes/_authenticated/cities'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedContactsIndexRouteImport } from './routes/_authenticated/contacts/index'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as AuthenticatedContactsNewRouteImport } from './routes/_authenticated/contacts/new'
import { Route as AuthenticatedContactsIdRouteImport } from './routes/_authenticated/contacts/$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubscriptionsRoute =
  AuthenticatedSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGuidaRoute = AuthenticatedGuidaRouteImport.update({
  id: '/guida',
  path: '/guida',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupsRoute = AuthenticatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCitiesRoute = AuthenticatedCitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactsIndexRoute =
  AuthenticatedContactsIndexRouteImport.update({
    id: '/contacts/',
    path: '/contacts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedContactsNewRoute =
  AuthenticatedContactsNewRouteImport.update({
    id: '/contacts/new',
    path: '/contacts/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContactsIdRoute = AuthenticatedContactsIdRouteImport.update({
  id: '/contacts/$id',
  path: '/contacts/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/cities': typeof AuthenticatedCitiesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/guida': typeof AuthenticatedGuidaRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/contacts/$id': typeof AuthenticatedContactsIdRoute
  '/contacts/new': typeof AuthenticatedContactsNewRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/contacts/': typeof AuthenticatedContactsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/cities': typeof AuthenticatedCitiesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/guida': typeof AuthenticatedGuidaRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/contacts/$id': typeof AuthenticatedContactsIdRoute
  '/contacts/new': typeof AuthenticatedContactsNewRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/contacts': typeof AuthenticatedContactsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/cities': typeof AuthenticatedCitiesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/groups': typeof AuthenticatedGroupsRoute
  '/_authenticated/guida': typeof AuthenticatedGuidaRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/contacts/$id': typeof AuthenticatedContactsIdRoute
  '/_authenticated/contacts/new': typeof AuthenticatedContactsNewRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/_authenticated/contacts/': typeof AuthenticatedContactsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/audit'
    | '/cities'
    | '/dashboard'
    | '/groups'
    | '/guida'
    | '/profile'
    | '/subscriptions'
    | '/users'
    | '/contacts/$id'
    | '/contacts/new'
    | '/api/public/contact'
    | '/contacts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app'
    | '/audit'
    | '/cities'
    | '/dashboard'
    | '/groups'
    | '/guida'
    | '/profile'
    | '/subscriptions'
    | '/users'
    | '/contacts/$id'
    | '/contacts/new'
    | '/api/public/contact'
    | '/contacts'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/audit'
    | '/_authenticated/cities'
    | '/_authenticated/dashboard'
    | '/_authenticated/groups'
    | '/_authenticated/guida'
    | '/_authenticated/profile'
    | '/_authenticated/subscriptions'
    | '/_authenticated/users'
    | '/_authenticated/contacts/$id'
    | '/_authenticated/contacts/new'
    | '/api/public/contact'
    | '/_authenticated/contacts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscriptions': {
      id: '/_authenticated/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof AuthenticatedSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guida': {
      id: '/_authenticated/guida'
      path: '/guida'
      fullPath: '/guida'
      preLoaderRoute: typeof AuthenticatedGuidaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups': {
      id: '/_authenticated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cities': {
      id: '/_authenticated/cities'
      path: '/cities'
      fullPath: '/cities'
      preLoaderRoute: typeof AuthenticatedCitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts/': {
      id: '/_authenticated/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AuthenticatedContactsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/contacts/new': {
      id: '/_authenticated/contacts/new'
      path: '/contacts/new'
      fullPath: '/contacts/new'
      preLoaderRoute: typeof AuthenticatedContactsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts/$id': {
      id: '/_authenticated/contacts/$id'
      path: '/contacts/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof AuthenticatedContactsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedCitiesRoute: typeof AuthenticatedCitiesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGroupsRoute: typeof AuthenticatedGroupsRoute
  AuthenticatedGuidaRoute: typeof AuthenticatedGuidaRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSubscriptionsRoute: typeof AuthenticatedSubscriptionsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedContactsIdRoute: typeof AuthenticatedContactsIdRoute
  AuthenticatedContactsNewRoute: typeof AuthenticatedContactsNewRoute
  AuthenticatedContactsIndexRoute: typeof AuthenticatedContactsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedCitiesRoute: AuthenticatedCitiesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGroupsRoute: AuthenticatedGroupsRoute,
  AuthenticatedGuidaRoute: AuthenticatedGuidaRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSubscriptionsRoute: AuthenticatedSubscriptionsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedContactsIdRoute: AuthenticatedContactsIdRoute,
  AuthenticatedContactsNewRoute: AuthenticatedContactsNewRoute,
  AuthenticatedContactsIndexRoute: AuthenticatedContactsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
